project_id = "your-project-id"

[functions.ai-analysis]
verify_jwt = false

[functions.anomaly-alert]
verify_jwt = false

[functions.aura-chat]
verify_jwt = true

[functions.splunk-webhook]
verify_jwt = false

[functions.firewall-control]
verify_jwt = false

[functions.metrics-ingest]
verify_jwt = false

[functions.send-otp]
verify_jwt = false
