// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drwbehbecdrlklqydmbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyd2JlaGJlY2RybGtscXlkbWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODk5NTcsImV4cCI6MjA3MzI2NTk1N30.KoG13tnsj78cVJy-WqJl13uoYZL50LUb6U-eSwVyrGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});